#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AkAudio

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "MovieScene_structs.hpp"


SDK_NAMESPACE_START

// Enum AkAudio.EAkCallbackType
// NumValues: 0x000E
enum class EAkCallbackType : uint8
{
	EndOfEvent                               = 0,
	Marker                                   = 2,
	Duration                                 = 3,
	Starvation                               = 5,
	MusicPlayStarted                         = 7,
	MusicSyncBeat                            = 8,
	MusicSyncBar                             = 9,
	MusicSyncEntry                           = 10,
	MusicSyncExit                            = 11,
	MusicSyncGrid                            = 12,
	MusicSyncUserCue                         = 13,
	MusicSyncPoint                           = 14,
	MIDIEvent                                = 16,
	EAkCallbackType_MAX                      = 17,
};

// Enum AkAudio.EAkResult
// NumValues: 0x003B
enum class EAkResult : uint8
{
	NotImplemented                           = 0,
	Success                                  = 1,
	Fail                                     = 2,
	PartialSuccess                           = 3,
	NotCompatible                            = 4,
	AlreadyConnected                         = 5,
	InvalidFile                              = 7,
	AudioFileHeaderTooLarge                  = 8,
	MaxReached                               = 9,
	InvalidID                                = 14,
	IDNotFound                               = 15,
	InvalidInstanceID                        = 16,
	NoMoreData                               = 17,
	InvalidStateGroup                        = 20,
	ChildAlreadyHasAParent                   = 21,
	InvalidLanguage                          = 22,
	CannotAddItseflAsAChild                  = 23,
	InvalidParameter                         = 31,
	ElementAlreadyInList                     = 35,
	PathNotFound                             = 36,
	PathNoVertices                           = 37,
	PathNotRunning                           = 38,
	PathNotPaused                            = 39,
	PathNodeAlreadyInList                    = 40,
	PathNodeNotInList                        = 41,
	DataNeeded                               = 43,
	NoDataNeeded                             = 44,
	DataReady                                = 45,
	NoDataReady                              = 46,
	InsufficientMemory                       = 52,
	Cancelled                                = 53,
	UnknownBankID                            = 54,
	BankReadError                            = 56,
	InvalidSwitchType                        = 57,
	FormatNotReady                           = 63,
	WrongBankVersion                         = 64,
	FileNotFound                             = 66,
	DeviceNotReady                           = 67,
	BankAlreadyLoaded                        = 69,
	RenderedFX                               = 71,
	ProcessNeeded                            = 72,
	ProcessDone                              = 73,
	MemManagerNotInitialized                 = 74,
	StreamMgrNotInitialized                  = 75,
	SSEInstructionsNotSupported              = 76,
	Busy                                     = 77,
	UnsupportedChannelConfig                 = 78,
	PluginMediaNotAvailable                  = 79,
	MustBeVirtualized                        = 80,
	CommandTooLarge                          = 81,
	RejectedByFilter                         = 82,
	InvalidCustomPlatformName                = 83,
	DLLCannotLoad                            = 84,
	DLLPathNotFound                          = 85,
	NoJavaVM                                 = 86,
	OpenSLError                              = 87,
	PluginNotRegistered                      = 88,
	DataAlignmentError                       = 89,
	EAkResult_MAX                            = 90,
};

// Enum AkAudio.EReflectionFilterBits
// NumValues: 0x0004
enum class EReflectionFilterBits : uint8
{
	Wall                                     = 0,
	Ceiling                                  = 1,
	Floor                                    = 2,
	EReflectionFilterBits_MAX                = 3,
};

// Enum AkAudio.AkCodecId
// NumValues: 0x0014
enum class EAkCodecId : uint8
{
	Bank                                     = 0,
	PCM                                      = 1,
	ADPCM                                    = 2,
	XMA                                      = 3,
	Vorbis                                   = 4,
	WiiADPCM                                 = 5,
	PCMEX                                    = 7,
	ExternalSource                           = 8,
	XWMA                                     = 9,
	AAC                                      = 10,
	FilePackage                              = 11,
	ATRAC9                                   = 12,
	VAG                                      = 13,
	ProfilerCapture                          = 14,
	AnalysisFile                             = 15,
	MIDI                                     = 16,
	OpusNX                                   = 17,
	CAF                                      = 18,
	AkOpus                                   = 19,
	AkCodecId_MAX                            = 20,
};

// Enum AkAudio.EAkMidiCcValues
// NumValues: 0x0062
enum class EAkMidiCcValues : uint8
{
	AkMidiCcBankSelectCoarse                 = 0,
	AkMidiCcModWheelCoarse                   = 1,
	AkMidiCcBreathCtrlCoarse                 = 2,
	AkMidiCcCtrl3Coarse                      = 3,
	AkMidiCcFootPedalCoarse                  = 4,
	AkMidiCcPortamentoCoarse                 = 5,
	AkMidiCcDataEntryCoarse                  = 6,
	AkMidiCcVolumeCoarse                     = 7,
	AkMidiCcBalanceCoarse                    = 8,
	AkMidiCcCtrl9Coarse                      = 9,
	AkMidiCcPanPositionCoarse                = 10,
	AkMidiCcExpressionCoarse                 = 11,
	AkMidiCcEffectCtrl1Coarse                = 12,
	AkMidiCcEffectCtrl2Coarse                = 13,
	AkMidiCcCtrl14Coarse                     = 14,
	AkMidiCcCtrl15Coarse                     = 15,
	AkMidiCcGenSlider1                       = 16,
	AkMidiCcGenSlider2                       = 17,
	AkMidiCcGenSlider3                       = 18,
	AkMidiCcGenSlider4                       = 19,
	AkMidiCcCtrl20Coarse                     = 20,
	AkMidiCcCtrl21Coarse                     = 21,
	AkMidiCcCtrl22Coarse                     = 22,
	AkMidiCcCtrl23Coarse                     = 23,
	AkMidiCcCtrl24Coarse                     = 24,
	AkMidiCcCtrl25Coarse                     = 25,
	AkMidiCcCtrl26Coarse                     = 26,
	AkMidiCcCtrl27Coarse                     = 27,
	AkMidiCcCtrl28Coarse                     = 28,
	AkMidiCcCtrl29Coarse                     = 29,
	AkMidiCcCtrl30Coarse                     = 30,
	AkMidiCcCtrl31Coarse                     = 31,
	AkMidiCcBankSelectFine                   = 32,
	AkMidiCcModWheelFine                     = 33,
	AkMidiCcBreathCtrlFine                   = 34,
	AkMidiCcCtrl3Fine                        = 35,
	AkMidiCcFootPedalFine                    = 36,
	AkMidiCcPortamentoFine                   = 37,
	AkMidiCcDataEntryFine                    = 38,
	AkMidiCcVolumeFine                       = 39,
	AkMidiCcBalanceFine                      = 40,
	AkMidiCcCtrl9Fine                        = 41,
	AkMidiCcPanPositionFine                  = 42,
	AkMidiCcExpressionFine                   = 43,
	AkMidiCcEffectCtrl1Fine                  = 44,
	AkMidiCcEffectCtrl2Fine                  = 45,
	AkMidiCcCtrl14Fine                       = 46,
	AkMidiCcCtrl15Fine                       = 47,
	AkMidiCcCtrl20Fine                       = 52,
	AkMidiCcCtrl21Fine                       = 53,
	AkMidiCcCtrl22Fine                       = 54,
	AkMidiCcCtrl23Fine                       = 55,
	AkMidiCcCtrl24Fine                       = 56,
	AkMidiCcCtrl25Fine                       = 57,
	AkMidiCcCtrl26Fine                       = 58,
	AkMidiCcCtrl27Fine                       = 59,
	AkMidiCcCtrl28Fine                       = 60,
	AkMidiCcCtrl29Fine                       = 61,
	AkMidiCcCtrl30Fine                       = 62,
	AkMidiCcCtrl31Fine                       = 63,
	AkMidiCcHoldPedal                        = 64,
	AkMidiCcPortamentoOnOff                  = 65,
	AkMidiCcSustenutoPedal                   = 66,
	AkMidiCcSoftPedal                        = 67,
	AkMidiCcLegatoPedal                      = 68,
	AkMidiCcHoldPedal2                       = 69,
	AkMidiCcSoundVariation                   = 70,
	AkMidiCcSoundTimbre                      = 71,
	AkMidiCcSoundReleaseTime                 = 72,
	AkMidiCcSoundAttackTime                  = 73,
	AkMidiCcSoundBrightness                  = 74,
	AkMidiCcSoundCtrl6                       = 75,
	AkMidiCcSoundCtrl7                       = 76,
	AkMidiCcSoundCtrl8                       = 77,
	AkMidiCcSoundCtrl9                       = 78,
	AkMidiCcSoundCtrl10                      = 79,
	AkMidiCcGeneralButton1                   = 80,
	AkMidiCcGeneralButton2                   = 81,
	AkMidiCcGeneralButton3                   = 82,
	AkMidiCcGeneralButton4                   = 83,
	AkMidiCcReverbLevel                      = 91,
	AkMidiCcTremoloLevel                     = 92,
	AkMidiCcChorusLevel                      = 93,
	AkMidiCcCelesteLevel                     = 94,
	AkMidiCcPhaserLevel                      = 95,
	AkMidiCcDataButtonP1                     = 96,
	AkMidiCcDataButtonM1                     = 97,
	AkMidiCcNonRegisterCoarse                = 98,
	AkMidiCcNonRegisterFine                  = 99,
	AkMidiCcAllSoundOff                      = 120,
	AkMidiCcAllControllersOff                = 121,
	AkMidiCcLocalKeyboard                    = 122,
	AkMidiCcAllNotesOff                      = 123,
	AkMidiCcOmniModeOff                      = 124,
	AkMidiCcOmniModeOn                       = 125,
	AkMidiCcOmniMonophonicOn                 = 126,
	AkMidiCcOmniPolyphonicOn                 = 127,
	EAkMidiCcValues_MAX                      = 128,
};

// Enum AkAudio.EAkMidiEventType
// NumValues: 0x000C
enum class EAkMidiEventType : uint8
{
	AkMidiEventTypeInvalid                   = 0,
	AkMidiEventTypeNoteOff                   = 128,
	AkMidiEventTypeNoteOn                    = 144,
	AkMidiEventTypeNoteAftertouch            = 160,
	AkMidiEventTypeController                = 176,
	AkMidiEventTypeProgramChange             = 192,
	AkMidiEventTypeChannelAftertouch         = 208,
	AkMidiEventTypePitchBend                 = 224,
	AkMidiEventTypeSysex                     = 240,
	AkMidiEventTypeEscape                    = 247,
	AkMidiEventTypeMeta                      = 255,
	EAkMidiEventType_MAX                     = 256,
};

// Enum AkAudio.ERTPCValueType
// NumValues: 0x0006
enum class ERTPCValueType : uint8
{
	Default                                  = 0,
	Global                                   = 1,
	GameObject                               = 2,
	PlayingID                                = 3,
	Unavailable                              = 4,
	ERTPCValueType_MAX                       = 5,
};

// Enum AkAudio.EAkCurveInterpolation
// NumValues: 0x000C
enum class EAkCurveInterpolation : uint8
{
	Log3                                     = 0,
	Sine                                     = 1,
	Log1                                     = 2,
	InvSCurve                                = 3,
	Linear                                   = 4,
	SCurve                                   = 5,
	Exp1                                     = 6,
	SineRecip                                = 7,
	Exp3                                     = 8,
	LastFadeCurve                            = 8,
	Constant                                 = 9,
	EAkCurveInterpolation_MAX                = 10,
};

// Enum AkAudio.AkActionOnEventType
// NumValues: 0x0006
enum class EAkActionOnEventType : uint8
{
	Stop                                     = 0,
	Pause                                    = 1,
	Resume                                   = 2,
	Break                                    = 3,
	ReleaseEnvelope                          = 4,
	AkActionOnEventType_MAX                  = 5,
};

// Enum AkAudio.AkMultiPositionType
// NumValues: 0x0004
enum class EAkMultiPositionType : uint8
{
	SingleSource                             = 0,
	MultiSources                             = 1,
	MultiDirections                          = 2,
	AkMultiPositionType_MAX                  = 3,
};

// Enum AkAudio.AkSpeakerConfiguration
// NumValues: 0x0011
enum class EAkSpeakerConfiguration : uint32
{
	Ak_Speaker_Front_Left                    = 1,
	Ak_Speaker_Front_Right                   = 2,
	Ak_Speaker_Front_Center                  = 4,
	Ak_Speaker_Low_Frequency                 = 8,
	Ak_Speaker_Back_Left                     = 16,
	Ak_Speaker_Back_Right                    = 32,
	Ak_Speaker_Back_Center                   = 256,
	Ak_Speaker_Side_Left                     = 512,
	Ak_Speaker_Side_Right                    = 1024,
	Ak_Speaker_Top                           = 2048,
	Ak_Speaker_Height_Front_Left             = 4096,
	Ak_Speaker_Height_Front_Center           = 8192,
	Ak_Speaker_Height_Front_Right            = 16384,
	Ak_Speaker_Height_Back_Left              = 32768,
	Ak_Speaker_Height_Back_Center            = 65536,
	Ak_Speaker_Height_Back_Right             = 131072,
	Ak_Speaker_MAX                           = 131073,
};

// Enum AkAudio.AkChannelConfiguration
// NumValues: 0x0017
enum class EAkChannelConfiguration : uint8
{
	Ak_Parent                                = 0,
	Ak_LFE                                   = 1,
	Ak_1_0                                   = 2,
	Ak_2_0                                   = 3,
	Ak_2_1                                   = 4,
	Ak_3_0                                   = 5,
	Ak_3_1                                   = 6,
	Ak_4_0                                   = 7,
	Ak_4_1                                   = 8,
	Ak_5_0                                   = 9,
	Ak_5_1                                   = 10,
	Ak_7_1                                   = 11,
	Ak_5_1_2                                 = 12,
	Ak_7_1_2                                 = 13,
	Ak_7_1_4                                 = 14,
	Ak_Auro_9_1                              = 15,
	Ak_Auro_10_1                             = 16,
	Ak_Auro_11_1                             = 17,
	Ak_Auro_13_1                             = 18,
	Ak_Ambisonics_1st_order                  = 19,
	Ak_Ambisonics_2nd_order                  = 20,
	Ak_Ambisonics_3rd_order                  = 21,
	Ak_MAX                                   = 22,
};

// Enum AkAudio.AkAcousticPortalState
// NumValues: 0x0003
enum class EAkAcousticPortalState : uint8
{
	Closed                                   = 0,
	Open                                     = 1,
	AkAcousticPortalState_MAX                = 2,
};

// Enum AkAudio.PanningRule
// NumValues: 0x0003
enum class EPanningRule : uint8
{
	PanningRule_Speakers                     = 0,
	PanningRule_Headphones                   = 1,
	PanningRule_MAX                          = 2,
};

// Enum AkAudio.EAkChannelMask
// NumValues: 0x0011
enum class EAkChannelMask : uint8
{
	FrontLeft                                = 0,
	FrontRight                               = 1,
	FrontCenter                              = 2,
	LowFrequency                             = 3,
	BackLeft                                 = 4,
	BackRight                                = 5,
	BackCenter                               = 8,
	SideLeft                                 = 9,
	SideRight                                = 10,
	Top                                      = 11,
	HeightFrontLeft                          = 12,
	HeightFrontCenter                        = 13,
	HeightFrontRight                         = 14,
	HeightBackLeft                           = 15,
	HeightBackCenter                         = 16,
	HeightBackRight                          = 17,
	EAkChannelMask_MAX                       = 18,
};

// Enum AkAudio.EAkChannelConfigType
// NumValues: 0x0004
enum class EAkChannelConfigType : uint32
{
	Anonymous                                = 0,
	Standard                                 = 1,
	Ambisonic                                = 2,
	EAkChannelConfigType_MAX                 = 3,
};

// Enum AkAudio.EAkDiffractionFlags
// NumValues: 0x0004
enum class EAkDiffractionFlags : uint8
{
	UseBuiltInParam                          = 0,
	UseObstruction                           = 1,
	CalcEmitterVirtualPosition               = 3,
	EAkDiffractionFlags_MAX                  = 4,
};

// Enum AkAudio.EAkPanningRule
// NumValues: 0x0003
enum class EAkPanningRule : uint32
{
	Speakers                                 = 0,
	Headphones                               = 1,
	EAkPanningRule_MAX                       = 2,
};

// Enum AkAudio.EAkAudioSessionMode
// NumValues: 0x0008
enum class EAkAudioSessionMode : uint32
{
	Default                                  = 0,
	VoiceChat                                = 1,
	GameChat                                 = 2,
	VideoRecording                           = 3,
	Measurement                              = 4,
	MoviePlayback                            = 5,
	VideoChat                                = 6,
	EAkAudioSessionMode_MAX                  = 7,
};

// Enum AkAudio.EAkAudioSessionCategoryOptions
// NumValues: 0x0005
enum class EAkAudioSessionCategoryOptions : uint8
{
	MixWithOthers                            = 0,
	DuckOthers                               = 1,
	AllowBluetooth                           = 2,
	DefaultToSpeaker                         = 3,
	EAkAudioSessionCategoryOptions_MAX       = 4,
};

// Enum AkAudio.EAkAudioSessionCategory
// NumValues: 0x0004
enum class EAkAudioSessionCategory : uint32
{
	Ambient                                  = 0,
	SoloAmbient                              = 1,
	PlayAndRecord                            = 2,
	EAkAudioSessionCategory_MAX              = 3,
};

// Enum AkAudio.EAkWindowsAudioAPI
// NumValues: 0x0004
enum class EAkWindowsAudioAPI : uint8
{
	Wasapi                                   = 0,
	XAudio2                                  = 1,
	DirectSound                              = 2,
	EAkWindowsAudioAPI_MAX                   = 3,
};

// Enum AkAudio.SD3DMultiplePositionsType
// NumValues: 0x0004
enum class ESD3DMultiplePositionsType : uint8
{
	SD3DMultiplePositions_Disabled           = 0,
	SD3DMultiplePositions_MultiSources       = 1,
	SD3DMultiplePositions_MultiDirections    = 2,
	SD3DMultiplePositions_MAX                = 3,
};

// Enum AkAudio.SD3DSoundMode
// NumValues: 0x0003
enum class ESD3DSoundMode : uint8
{
	SD3DMode_Normal                          = 0,
	SD3DMode_Random                          = 1,
	SD3DMode_MAX                             = 2,
};

// Enum AkAudio.ListenerPositioningMode
// NumValues: 0x0004
enum class EListenerPositioningMode : uint8
{
	LPM_Camera                               = 0,
	LPM_Player                               = 1,
	LPM_Dynamic                              = 2,
	LPM_MAX                                  = 3,
};

// Enum AkAudio.SDCurveType
// NumValues: 0x0003
enum class ESDCurveType : uint8
{
	SDCurve_Linear                           = 0,
	SDCurve_Sine                             = 1,
	SDCurve_MAX                              = 2,
};

// Enum AkAudio.SDVolumeType
// NumValues: 0x0003
enum class ESDVolumeType : uint8
{
	SDVolume_Sphere                          = 0,
	SDVolume_Cylinder                        = 1,
	SDVolume_MAX                             = 2,
};

// ScriptStruct AkAudio.AkMainOutputSettings
// 0x0028 (0x0028 - 0x0000)
struct FAkMainOutputSettings final
{
public:
	class FString                                 AudioDeviceShareset;                               // 0x0000(0x0010)(Edit, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint32                                        DeviceID;                                          // 0x0010(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EAkPanningRule                                PanningRule;                                       // 0x0014(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EAkChannelConfigType                          ChannelConfigType;                                 // 0x0018(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint32                                        ChannelMask;                                       // 0x001C(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint32                                        NumberOfChannels;                                  // 0x0020(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FAkMainOutputSettings;

// ScriptStruct AkAudio.AkSpatialAudioSettings
// 0x0010 (0x0010 - 0x0000)
struct FAkSpatialAudioSettings final
{
public:
	uint32                                        SpatialAudioPoolSize;                              // 0x0000(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint32                                        MaxSoundPropagationDepth;                          // 0x0004(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint32                                        DiffractionFlags;                                  // 0x0008(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         MovementThreshold;                                 // 0x000C(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FAkSpatialAudioSettings;

// ScriptStruct AkAudio.AkCommonInitializationSettings
// 0x0068 (0x0068 - 0x0000)
struct FAkCommonInitializationSettings
{
public:
	uint32                                        MaximumNumberOfMemoryPools;                        // 0x0000(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint32                                        MaximumNumberOfPositioningPaths;                   // 0x0004(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint32                                        DefaultPoolSize;                                   // 0x0008(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         MemoryCutoffThreshold;                             // 0x000C(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint32                                        CommandQueueSize;                                  // 0x0010(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint32                                        SamplesPerFrame;                                   // 0x0014(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FAkMainOutputSettings                  MainOutputSettings;                                // 0x0018(0x0028)(Edit, NativeAccessSpecifierPublic)
	float                                         StreamingLookAheadRatio;                           // 0x0040(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint32                                        StreamManagerPoolSize;                             // 0x0044(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint32                                        LowerEnginePoolSize;                               // 0x0048(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         LowerEngineMemoryCutoffThreshold;                  // 0x004C(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint16                                        NumberOfRefillsInVoice;                            // 0x0050(0x0002)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_52[0x2];                                       // 0x0052(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAkSpatialAudioSettings                SpatialAudioSettings;                              // 0x0054(0x0010)(Edit, NoDestructor, NativeAccessSpecifierPublic)
	uint8                                         Pad_64[0x4];                                       // 0x0064(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FAkCommonInitializationSettings;

// ScriptStruct AkAudio.AKWaapiJsonObject
// 0x0010 (0x0010 - 0x0000)
struct alignas(0x08) FAKWaapiJsonObject final
{
public:
	uint8                                         Pad_0[0x10];                                       // 0x0000(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FAKWaapiJsonObject;

// ScriptStruct AkAudio.SubtitlesTrack
// 0x0040 (0x0040 - 0x0000)
struct alignas(0x08) FSubtitlesTrack final
{
public:
	uint8                                         Pad_0[0x38];                                       // 0x0000(0x0038)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         StartFrame;                                        // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         EndFrame;                                          // 0x003C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FSubtitlesTrack;

// ScriptStruct AkAudio.AkExternalSourceInfo
// 0x0028 (0x0028 - 0x0000)
struct FAkExternalSourceInfo final
{
public:
	class FString                                 ExternalSrcName;                                   // 0x0000(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EAkCodecId                                    CodecID;                                           // 0x0010(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 Filename;                                          // 0x0018(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FAkExternalSourceInfo;

// ScriptStruct AkAudio.AkWaapiSubscriptionId
// 0x0008 (0x0008 - 0x0000)
struct alignas(0x08) FAkWaapiSubscriptionId final
{
public:
	uint8                                         Pad_0[0x8];                                        // 0x0000(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FAkWaapiSubscriptionId;

// ScriptStruct AkAudio.AkAdvancedSpatialAudioSettings
// 0x0008 (0x0008 - 0x0000)
struct FAkAdvancedSpatialAudioSettings final
{
public:
	float                                         DiffractionShadowAttenuationFactor;                // 0x0000(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         DiffractionShadowDegrees;                          // 0x0004(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FAkAdvancedSpatialAudioSettings;

// ScriptStruct AkAudio.AkAdvancedInitializationSettings
// 0x0030 (0x0030 - 0x0000)
struct FAkAdvancedInitializationSettings
{
public:
	uint32                                        IO_MemorySize;                                     // 0x0000(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         TargetAutoStreamBufferLength;                      // 0x0004(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          UseStreamCache;                                    // 0x0008(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	uint32                                        MaximumPinnedBytesInCache;                         // 0x000C(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         PrepareEventMemoryPoolID;                          // 0x0010(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          EnableGameSyncPreparation;                         // 0x0014(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_15[0x3];                                       // 0x0015(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	uint32                                        ContinuousPlaybackLookAhead;                       // 0x0018(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint32                                        MonitorPoolSize;                                   // 0x001C(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint32                                        MonitorQueuePoolSize;                              // 0x0020(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint32                                        MaximumHardwareTimeoutMs;                          // 0x0024(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FAkAdvancedSpatialAudioSettings        SpatialAudioSettings;                              // 0x0028(0x0008)(Edit, NoDestructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FAkAdvancedInitializationSettings;

// ScriptStruct AkAudio.AkAdvancedInitializationSettingsWithMultiCoreRendering
// 0x0004 (0x0034 - 0x0030)
struct FAkAdvancedInitializationSettingsWithMultiCoreRendering : public FAkAdvancedInitializationSettings
{
public:
	bool                                          EnableMultiCoreRendering;                          // 0x0030(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_31[0x3];                                       // 0x0031(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FAkAdvancedInitializationSettingsWithMultiCoreRendering;

// ScriptStruct AkAudio.AkWindowsAdvancedInitializationSettings
// 0x0008 (0x003C - 0x0034)
struct FAkWindowsAdvancedInitializationSettings final : public FAkAdvancedInitializationSettingsWithMultiCoreRendering
{
public:
	uint32                                        AudioAPI;                                          // 0x0034(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          GlobalFocus;                                       // 0x0038(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          UseHeadMountedDisplayAudioDevice;                  // 0x0039(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_3A[0x2];                                       // 0x003A(0x0002)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FAkWindowsAdvancedInitializationSettings;

// ScriptStruct AkAudio.AkAmbSoundCheckpointRecord
// 0x0001 (0x0001 - 0x0000)
struct FAkAmbSoundCheckpointRecord final
{
public:
	bool                                          bCurrentlyPlaying;                                 // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FAkAmbSoundCheckpointRecord;

// ScriptStruct AkAudio.AkXboxOneApuHeapInitializationSettings
// 0x0008 (0x0008 - 0x0000)
struct FAkXboxOneApuHeapInitializationSettings final
{
public:
	uint32                                        CachedSize;                                        // 0x0000(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint32                                        NonCachedSize;                                     // 0x0004(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FAkXboxOneApuHeapInitializationSettings;

// ScriptStruct AkAudio.AkAndroidAdvancedInitializationSettings
// 0x0004 (0x0038 - 0x0034)
struct FAkAndroidAdvancedInitializationSettings final : public FAkAdvancedInitializationSettingsWithMultiCoreRendering
{
public:
	bool                                          RoundFrameSizeToHardwareSize;                      // 0x0034(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_35[0x3];                                       // 0x0035(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FAkAndroidAdvancedInitializationSettings;

// ScriptStruct AkAudio.AkSegmentInfo
// 0x0024 (0x0024 - 0x0000)
struct FAkSegmentInfo final
{
public:
	int32                                         CurrentPosition;                                   // 0x0000(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         PreEntryDuration;                                  // 0x0004(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ActiveDuration;                                    // 0x0008(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         PostExitDuration;                                  // 0x000C(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         RemainingLookAheadTime;                            // 0x0010(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         BeatDuration;                                      // 0x0014(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         BarDuration;                                       // 0x0018(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         GridDuration;                                      // 0x001C(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         GridOffset;                                        // 0x0020(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FAkSegmentInfo;

// ScriptStruct AkAudio.AkMidiEventBase
// 0x0002 (0x0002 - 0x0000)
struct FAkMidiEventBase
{
public:
	EAkMidiEventType                              Type;                                              // 0x0000(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Chan;                                              // 0x0001(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FAkMidiEventBase;

// ScriptStruct AkAudio.AkMidiProgramChange
// 0x0001 (0x0003 - 0x0002)
struct FAkMidiProgramChange final : public FAkMidiEventBase
{
public:
	uint8                                         ProgramNum;                                        // 0x0002(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FAkMidiProgramChange;

// ScriptStruct AkAudio.AkMidiChannelAftertouch
// 0x0001 (0x0003 - 0x0002)
struct FAkMidiChannelAftertouch final : public FAkMidiEventBase
{
public:
	uint8                                         Value;                                             // 0x0002(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FAkMidiChannelAftertouch;

// ScriptStruct AkAudio.AkMidiNoteAftertouch
// 0x0002 (0x0004 - 0x0002)
struct FAkMidiNoteAftertouch final : public FAkMidiEventBase
{
public:
	uint8                                         Note;                                              // 0x0002(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Value;                                             // 0x0003(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FAkMidiNoteAftertouch;

// ScriptStruct AkAudio.AkPS4AdvancedInitializationSettings
// 0x0008 (0x003C - 0x0034)
struct FAkPS4AdvancedInitializationSettings final : public FAkAdvancedInitializationSettingsWithMultiCoreRendering
{
public:
	uint32                                        ACPBatchBufferSize;                                // 0x0034(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          UseHardwareCodecLowLatencyMode;                    // 0x0038(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_39[0x3];                                       // 0x0039(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FAkPS4AdvancedInitializationSettings;

// ScriptStruct AkAudio.AkMidiPitchBend
// 0x0006 (0x0008 - 0x0002)
struct FAkMidiPitchBend final : public FAkMidiEventBase
{
public:
	uint8                                         ValueLsb;                                          // 0x0002(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         ValueMsb;                                          // 0x0003(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         FullValue;                                         // 0x0004(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FAkMidiPitchBend;

// ScriptStruct AkAudio.AkMidiCc
// 0x0002 (0x0004 - 0x0002)
struct FAkMidiCc final : public FAkMidiEventBase
{
public:
	EAkMidiCcValues                               Cc;                                                // 0x0002(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Value;                                             // 0x0003(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FAkMidiCc;

// ScriptStruct AkAudio.AkMidiNoteOnOff
// 0x0002 (0x0004 - 0x0002)
struct FAkMidiNoteOnOff final : public FAkMidiEventBase
{
public:
	uint8                                         Note;                                              // 0x0002(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Velocity;                                          // 0x0003(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FAkMidiNoteOnOff;

// ScriptStruct AkAudio.AkMidiGeneric
// 0x0002 (0x0004 - 0x0002)
struct FAkMidiGeneric final : public FAkMidiEventBase
{
public:
	uint8                                         Param1;                                            // 0x0002(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Param2;                                            // 0x0003(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FAkMidiGeneric;

// ScriptStruct AkAudio.AkChannelMask
// 0x0004 (0x0004 - 0x0000)
struct FAkChannelMask final
{
public:
	int32                                         ChannelMask;                                       // 0x0000(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FAkChannelMask;

// ScriptStruct AkAudio.MarkerInfos
// 0x0018 (0x0018 - 0x0000)
struct FMarkerInfos final
{
public:
	class FString                                 Label;                                             // 0x0000(0x0010)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         PositionInMs;                                      // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FMarkerInfos;

// ScriptStruct AkAudio.AkCommonInitializationSettingsWithSampleRate
// 0x0008 (0x0070 - 0x0068)
struct FAkCommonInitializationSettingsWithSampleRate final : public FAkCommonInitializationSettings
{
public:
	uint32                                        SampleRate;                                        // 0x0068(0x0004)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_6C[0x4];                                       // 0x006C(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FAkCommonInitializationSettingsWithSampleRate;

// ScriptStruct AkAudio.AkCommunicationSettings
// 0x0020 (0x0020 - 0x0000)
struct FAkCommunicationSettings
{
public:
	uint32                                        PoolSize;                                          // 0x0000(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint16                                        DiscoveryBroadcastPort;                            // 0x0004(0x0002)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint16                                        CommandPort;                                       // 0x0006(0x0002)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint16                                        NotificationPort;                                  // 0x0008(0x0002)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_A[0x6];                                        // 0x000A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 NetworkName;                                       // 0x0010(0x0010)(Edit, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FAkCommunicationSettings;

// ScriptStruct AkAudio.AkCommunicationSettingsWithSystemInitialization
// 0x0008 (0x0028 - 0x0020)
struct FAkCommunicationSettingsWithSystemInitialization final : public FAkCommunicationSettings
{
public:
	bool                                          InitializeSystemComms;                             // 0x0020(0x0001)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FAkCommunicationSettingsWithSystemInitialization;

// ScriptStruct AkAudio.AkAudioSession
// 0x000C (0x000C - 0x0000)
struct FAkAudioSession final
{
public:
	EAkAudioSessionCategory                       AudioSessionCategory;                              // 0x0000(0x0004)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint32                                        AudioSessionCategoryOptions;                       // 0x0004(0x0004)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EAkAudioSessionMode                           AudioSessionMode;                                  // 0x0008(0x0004)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FAkAudioSession;

// ScriptStruct AkAudio.MovieSceneTangentDataSerializationHelper
// 0x0014 (0x0014 - 0x0000)
struct FMovieSceneTangentDataSerializationHelper final
{
public:
	float                                         ArriveTangent;                                     // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         LeaveTangent;                                      // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	ERichCurveTangentWeightMode                   TangentWeightMode;                                 // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         ArriveTangentWeight;                               // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         LeaveTangentWeight;                                // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FMovieSceneTangentDataSerializationHelper;

// ScriptStruct AkAudio.MovieSceneFloatValueSerializationHelper
// 0x001C (0x001C - 0x0000)
struct FMovieSceneFloatValueSerializationHelper final
{
public:
	float                                         Value;                                             // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	ERichCurveInterpMode                          InterpMode;                                        // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	ERichCurveTangentMode                         TangentMode;                                       // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_6[0x2];                                        // 0x0006(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FMovieSceneTangentDataSerializationHelper Tangent;                                        // 0x0008(0x0014)(NoDestructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FMovieSceneFloatValueSerializationHelper;

// ScriptStruct AkAudio.MovieSceneFloatChannelSerializationHelper
// 0x0030 (0x0030 - 0x0000)
struct FMovieSceneFloatChannelSerializationHelper final
{
public:
	ERichCurveExtrapolation                       PreInfinityExtrap;                                 // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	ERichCurveExtrapolation                       PostInfinityExtrap;                                // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2[0x6];                                        // 0x0002(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<int32>                                 Times;                                             // 0x0008(0x0010)(ZeroConstructor, NativeAccessSpecifierPublic)
	TArray<struct FMovieSceneFloatValueSerializationHelper> Values;                                  // 0x0018(0x0010)(ZeroConstructor, NativeAccessSpecifierPublic)
	float                                         DefaultValue;                                      // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bHasDefaultValue;                                  // 0x002C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2D[0x3];                                       // 0x002D(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FMovieSceneFloatChannelSerializationHelper;

// ScriptStruct AkAudio.AkBoolPropertyToControl
// 0x0010 (0x0010 - 0x0000)
struct FAkBoolPropertyToControl final
{
public:
	class FString                                 ItemProperty;                                      // 0x0000(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FAkBoolPropertyToControl;

// ScriptStruct AkAudio.AkPropertyToControl
// 0x0010 (0x0010 - 0x0000)
struct FAkPropertyToControl final
{
public:
	class FString                                 ItemProperty;                                      // 0x0000(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FAkPropertyToControl;

// ScriptStruct AkAudio.AkWwiseObjectDetails
// 0x0030 (0x0030 - 0x0000)
struct FAkWwiseObjectDetails final
{
public:
	class FString                                 ItemName;                                          // 0x0000(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ItemPath;                                          // 0x0010(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ItemId;                                            // 0x0020(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FAkWwiseObjectDetails;

// ScriptStruct AkAudio.AkWwiseItemToControl
// 0x0040 (0x0040 - 0x0000)
struct FAkWwiseItemToControl final
{
public:
	struct FAkWwiseObjectDetails                  ItemPicked;                                        // 0x0000(0x0030)(Edit, EditConst, NativeAccessSpecifierPublic)
	class FString                                 ItemPath;                                          // 0x0030(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FAkWwiseItemToControl;

// ScriptStruct AkAudio.AkPoly
// 0x0010 (0x0010 - 0x0000)
struct FAkPoly final
{
public:
	class UAkAcousticTexture*                     Texture;                                           // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          EnableSurface;                                     // 0x0008(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FAkPoly;

// ScriptStruct AkAudio.AkWaapiFieldNames
// 0x0010 (0x0010 - 0x0000)
struct FAkWaapiFieldNames final
{
public:
	class FString                                 FieldName;                                         // 0x0000(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FAkWaapiFieldNames;

// ScriptStruct AkAudio.AkWaapiUri
// 0x0010 (0x0010 - 0x0000)
struct FAkWaapiUri final
{
public:
	class FString                                 Uri;                                               // 0x0000(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FAkWaapiUri;

// ScriptStruct AkAudio.AkXboxOneAdvancedInitializationSettings
// 0x0008 (0x003C - 0x0034)
struct FAkXboxOneAdvancedInitializationSettings final : public FAkAdvancedInitializationSettingsWithMultiCoreRendering
{
public:
	uint32                                        ShapeDefaultPoolSize;                              // 0x0034(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint16                                        MaximumNumberOfXMAVoices;                          // 0x0038(0x0002)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          UseHardwareCodecLowLatencyMode;                    // 0x003A(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_3B[0x1];                                       // 0x003B(0x0001)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FAkXboxOneAdvancedInitializationSettings;

// ScriptStruct AkAudio.ReverbState
// 0x0028 (0x0028 - 0x0000)
struct alignas(0x08) FReverbState final
{
public:
	uint8                                         Pad_0[0x28];                                       // 0x0000(0x0028)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FReverbState;

// ScriptStruct AkAudio.VisemeNode
// 0x0008 (0x0008 - 0x0000)
struct FVisemeNode final
{
public:
	float                                         Timestamp;                                         // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Weight;                                            // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FVisemeNode;

// ScriptStruct AkAudio.VisemeTrack
// 0x0010 (0x0010 - 0x0000)
struct FVisemeTrack final
{
public:
	TArray<struct FVisemeNode>                    Nodes;                                             // 0x0000(0x0010)(ZeroConstructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FVisemeTrack;

// ScriptStruct AkAudio.AkAudioEventTrackKey
// 0x0040 (0x0040 - 0x0000)
struct FAkAudioEventTrackKey final
{
public:
	float                                         Time;                                              // 0x0000(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TSubclassOf<class UAkAudioEvent>              AkAudioEventTemplate;                              // 0x0008(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 EventName;                                         // 0x0010(0x0010)(Edit, BlueprintVisible, ZeroConstructor, EditConst, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         bPlayOnlyForward : 1;                              // 0x0020(0x0001)(BitIndex: 0x00, PropSize: 0x0001 (Edit, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic))
	uint8                                         bPlayOnlyBackward : 1;                             // 0x0020(0x0001)(BitIndex: 0x01, PropSize: 0x0001 (Edit, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic))
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UAkAudioEvent*                          AkAudioEvent;                                      // 0x0028(0x0008)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_30[0x10];                                      // 0x0030(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FAkAudioEventTrackKey;

// ScriptStruct AkAudio.DNECueTrackKey
// 0x0028 (0x0028 - 0x0000)
struct FDNECueTrackKey final
{
public:
	float                                         Time;                                              // 0x0000(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TSubclassOf<class UDNECue>                    EventTemplate;                                     // 0x0008(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UDNECue*                                Event;                                             // 0x0010(0x0008)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         bPlayOnlyForward : 1;                              // 0x0018(0x0001)(BitIndex: 0x00, PropSize: 0x0001 (Edit, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic))
	uint8                                         bPlayOnlyBackward : 1;                             // 0x0018(0x0001)(BitIndex: 0x01, PropSize: 0x0001 (Edit, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic))
	uint8                                         Pad_19[0x3];                                       // 0x0019(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         PlayingID;                                         // 0x001C(0x0004)(Edit, ZeroConstructor, Transient, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UAkComponent*                           AssociatedComponent;                               // 0x0020(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FDNECueTrackKey;

// ScriptStruct AkAudio.MovieSceneAkAudioEventTemplate
// 0x0008 (0x0028 - 0x0020)
struct FMovieSceneAkAudioEventTemplate final : public FMovieSceneEvalTemplate
{
public:
	class UMovieSceneAkAudioEventSection*         Section;                                           // 0x0020(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FMovieSceneAkAudioEventTemplate;

// ScriptStruct AkAudio.MovieSceneAkAudioRTPCTemplate
// 0x0008 (0x0028 - 0x0020)
struct FMovieSceneAkAudioRTPCTemplate final : public FMovieSceneEvalTemplate
{
public:
	class UMovieSceneAkAudioRTPCSection*          Section;                                           // 0x0020(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FMovieSceneAkAudioRTPCTemplate;

SDK_NAMESPACE_END
