#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// FORWARD DECLARATIONS


namespace UIObjectDescription_0_2 { class UUIObjectDescription_0_C; }

namespace UIObjectDescription_5_1 { class UUIObjectDescription_5_C; }

namespace UIObjectDescription_5_3 { class UUIObjectDescription_5_C; }

namespace UIObjectDescription_3 { class UUIObjectDescription_3_C; }

namespace UIObjectDescription_0_3 { class UUIObjectDescription_0_C; }

namespace UIObjectDescription_3_0 { class UUIObjectDescription_3_C; }

namespace UIObjectDescription_0_0 { class UUIObjectDescription_0_C; }

namespace UIObjectDescription_0_7 { class UUIObjectDescription_0_C; }

namespace UIObjectDescription_4_0 { class UUIObjectDescription_4_C; }

namespace UIObjectDescription_4 { class UUIObjectDescription_4_C; }

namespace UIObjectDescription_0 { class UUIObjectDescription_0_C; }

namespace UIObjectDescription_1 { class UUIObjectDescription_1_C; }

namespace UIObjectDescription_1_1 { class UUIObjectDescription_1_C; }

namespace UIObjectDescription_0_1 { class UUIObjectDescription_0_C; }

namespace UIObjectDescription_2_0 { class UUIObjectDescription_2_C; }

namespace UIObjectDescription_2 { class UUIObjectDescription_2_C; }

namespace UIObjectDescription_5 { class UUIObjectDescription_5_C; }

namespace UIObjectDescription_5_0 { class UUIObjectDescription_5_C; }

namespace UIObjectDescription_0_4 { class UUIObjectDescription_0_C; }

namespace UIObjectDescription_0_5 { class UUIObjectDescription_0_C; }

namespace UIObjectDescription_0_6 { class UUIObjectDescription_0_C; }

namespace UIObjectDescription_1_0 { class UUIObjectDescription_1_C; }

namespace UIObjectDescription_5_2 { class UUIObjectDescription_5_C; }

